[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Note: the scipy <1.14 requirement is because the version of
# strawberryfields on pypi is old and still has this issues
# https://github.com/XanaduAI/strawberryfields/issues/750
[project]
name = "photon_catalysis"
version = "0.1.0"
dependencies = [
    "sympy",
    "numpy",
    "jax",
    "optax",
    "scipy<1.14",
    "tqdm"
]
requires-python = ">=3.9"
description = "Code for \"Photon catalysis for general multimode multi-photon quantum state preparation\" paper."
authors = [
    {name = "Émilie Gillet", email = "emilie.gillet@etu.sorbonne-universite.fr"},
    {name = "Andrei Aralov", email = "andrei.aralov@etu.sorbonne-universite.fr"}
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]

[project.optional-dependencies]
boson_sampling = ["perceval-quandela", "matplotlib", "pandas"]
gaussian_boson_sampling = ["StrawberryFields", "matplotlib", "pandas"]
paper_results = ["pandas"]

[project.urls]
Homepage = "https://github.com/EQ15T/photon-catalysis"

[tool.hatch.metadata]
allow-direct-references = true
