on:
  push:
    branches:
      - master

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip wheel . -w wheels
      - name: Install and test
        run: |
          python -m pip install wheels/photon_catalysis-*-py3-none-any.whl
          python -m pytest test_photon_catalysis/test_optimal_preparation.py
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          path: wheels/photon_catalysis-*-py3-none-any.whl
